theme: minima
title: DamajaUK Portfolio

description: All GitHub personal development projects

# Plugins
plugins:
 - jekyll-paginate
 - jekyll-feed
 - jekyll-seo-tag
 
# Others
markdown: kramdown

minima:
  # Generate social links in footer
  social_links:
    twitter: d4majaUK
    github:  d4majaUK
    instagram: d4majaUK
    youtube: d4majaUK
