theme: minima
title: DamajaUK Portfolio
author: Anthony Barrett MBCS

description: DamajaUK GitHub development projects

# Plugins
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 
# Others
markdown: kramdown

minima:
  # Generate social links in footer
  social_links:
    email: "abarrett_mbcs@outlook.com"
    twitter: d4majaUK
    github:  d4majaUK
    instagram: d4majaUK
    youtube: d4majaUK

header_pages:
 - blog.html
 - history.md
 - about.md
