theme: minima
title: DamajaUK Portfolio

author:
  name: DamajaUK
  email: support@damaja.co.uk

description: All GitHub personal development projects

# Plugins
plugins:
  - jekyll-paginate

# Others
markdown: kramdown
