theme: minima
title: DamajaUK Portfolio

author:
  name: DamajaUK
  email: "d4maja@hotmail.com"
  
description: All GitHub personal development projects

# Plugins
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 
# Others
markdown: kramdown

minima:
  # Generate social links in footer
  social_links:
    twitter: d4majaUK
    github:  d4majaUK
    instagram: d4majaUK
    youtube: d4majaUK

header_pages:
 - blog.html
 - about.md
