theme: minima
title: DamajaUK Portfolio
description: All GitHub personal development projects

# Plugins
plugins:
  - jekyll-paginate

# Others
markdown: kramdown

author:
  name: DamajaUK
  email: "support@damaja.co.uk"
